<?php
/**
 * This file is part of the MageObsidian - ModernFrontend project.
 *
 * @license MIT License - See the LICENSE file in the root directory for details.
 * © 2024 Jeanmarcos Juarez
 */

declare(strict_types=1);

namespace MageObsidian\ModernFrontendCli\Console\Command;

use MageObsidian\ModernFrontendCli\Service\ScaffoldGenerator;
use MageObsidian\ModernFrontendCli\Utils\CustomSymfonyStyle;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Exception\FileSystemException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Scaffolds a new Magento module under app/code pre-wired for MageObsidian:
 * registration, module.xml (sequenced after the core), the compatibility opt-in,
 * and a web/module.config.ts. The module is invisible to the stack until it
 * ships the compatibility file, so it is generated by default.
 */
class GenerateModuleCommand extends Command
{
    private const string NAME_PATTERN = '/^[A-Z][A-Za-z0-9]+_[A-Z][A-Za-z0-9]+$/';

    public function __construct(
        private readonly DirectoryList $directoryList,
        private readonly ScaffoldGenerator $generator
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('mage-obsidian:generate:module')
             ->setDescription('Generate a new module under app/code pre-wired for the MageObsidian frontend.')
             ->addArgument('name', InputArgument::REQUIRED, 'Module name in Vendor_Module form.')
             ->addOption('force', 'f', InputOption::VALUE_NONE, 'Overwrite files if they already exist.');

        parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new CustomSymfonyStyle($input, $output);
        $name = (string)$input->getArgument('name');
        $force = (bool)$input->getOption('force');

        if (!preg_match(self::NAME_PATTERN, $name)) {
            $io->error(sprintf('Invalid module name "%s". Expected Vendor_Module (e.g. Acme_Catalog).', $name));
            return Command::FAILURE;
        }

        [$vendor, $module] = explode('_', $name, 2);
        $moduleDir = $this->directoryList->getRoot() . '/app/code/' . $vendor . '/' . $module;

        try {
            $files = [
                'registration.php' => 'module/registration.php.tpl',
                'etc/module.xml' => 'module/module.xml.tpl',
                'etc/mage_obsidian_compatibility.xml' => 'module/mage_obsidian_compatibility.xml.tpl',
                'view/frontend/web/module.config.ts' => 'module/module.config.ts.tpl',
            ];

            $replacements = ['MODULE_NAME' => $name, 'VENDOR' => $vendor, 'MODULE' => $module];
            $created = [];
            foreach ($files as $relative => $template) {
                $absolute = $moduleDir . '/' . $relative;
                if (!$this->generator->write($absolute, $this->generator->render($template, $replacements), $force)) {
                    $io->error(sprintf('%s already exists. Use --force to overwrite.', $absolute));
                    return Command::FAILURE;
                }
                $created[] = [$relative];
            }
        } catch (FileSystemException $e) {
            $io->error($e->getMessage());
            return Command::FAILURE;
        }

        $io->info(sprintf('Module %s created at %s', $name, $moduleDir));
        $io->table(['Files generated'], $created);
        $io->note(sprintf(
            "Next steps:\n"
            . "    bin/magento module:enable %s\n"
            . "    bin/magento setup:upgrade\n"
            . "    bin/magento mage-obsidian:frontend:config --generate\n"
            . "    bin/magento mage-obsidian:generate:component <Name> --module=%s",
            $name,
            $name
        ));

        return Command::SUCCESS;
    }
}
